apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p712mom8s-go
  janus-idp.io/tekton: p712mom8s-go
  backstage.io/kubernetes-id: p712mom8s-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p712mom8s-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
